typography_spectrum: 0.24804
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.326813
  lightness: 0.493421
  rhythmicContrast: 0.811678
  saturation: 0.3125
opengraph: {}
layout_spectrum: 0.25572
analytics: {}
author:
  name: Davide
  email: davide@mazzoni.us
name: DavideMazzoni
cta: {}
title: Emperor
purpose: []
