name: DavideMazzoni
favicon: null
layout_spectrum: 0.0904382518492639
typography_spectrum: 0.46469737868756056
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.326813816325739
  lightness: 0.9788501027505845
  saturation: 0.362439913675189
  rhythmicContrast: 0.8970725757535547
purpose: []
